apiRules:
- include:
    uidRegex: ^nickmaltbie\.StateMachineUnity
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.StateMachineUnity\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace